<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AdditionalJobsSeeder extends Seeder
{
    public function run()
    {
        $jobs = [
            [
                'title' => 'مهندس مدني - مشاريع البنية التحتية',
                'work_place' => 'الخبر، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 5,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مهندس مدني للعمل على مشاريع البنية التحتية الكبرى. المطلوب خبرة في تصميم الطرق والجسور وإدارة المشاريع الإنشائية.',
                'salary_min' => 8500,
                'salary_max' => 14000,
                'job_type' => 'دوام كامل',
                'skills' => 'AutoCAD, Civil 3D, Project Management, Structural Design',
                'requirements' => 'بكالوريوس هندسة مدنية، خبرة 5 سنوات، معرفة ببرامج التصميم',
                'status' => 'active'
            ],
            [
                'title' => 'أخصائي موارد بشرية',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'female',
                'education_level_id' => 1,
                'work_experience' => 3,
                'work_field_id' => 4,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'نبحث عن أخصائية موارد بشرية للانضمام لفريقنا. المطلوب خبرة في التوظيف، تطوير الموظفين، وإدارة الأداء.',
                'salary_min' => 6000,
                'salary_max' => 9000,
                'job_type' => 'دوام كامل',
                'skills' => 'التوظيف, تطوير الموظفين, قوانين العمل, تحليل الأداء',
                'requirements' => 'بكالوريوس إدارة أعمال أو موارد بشرية، خبرة 3 سنوات، مهارات تواصل ممتازة',
                'status' => 'active'
            ],
            [
                'title' => 'مطور ألعاب - Unity',
                'work_place' => 'عن بُعد',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 4,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مطور ألعاب محترف باستخدام Unity لتطوير ألعاب جوال وحاسوب. العمل عن بُعد مع فريق عالمي.',
                'salary_min' => 9000,
                'salary_max' => 15000,
                'job_type' => 'عن بُعد',
                'skills' => 'Unity, C#, Game Design, 3D Modeling, Animation',
                'requirements' => 'خبرة 4 سنوات في Unity، معرفة بـ C#، أمثلة على ألعاب منشورة',
                'status' => 'active'
            ],
            [
                'title' => 'صيدلاني إكلينيكي',
                'work_place' => 'مكة المكرمة، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 2,
                'work_field_id' => 6,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب صيدلاني إكلينيكي للعمل في مستشفى متخصص. المطلوب خبرة في الصيدلة الإكلينيكية ومراجعة الوصفات الطبية.',
                'salary_min' => 7000,
                'salary_max' => 10000,
                'job_type' => 'دوام كامل',
                'skills' => 'الصيدلة الإكلينيكية, مراجعة الوصفات, التفاعلات الدوائية',
                'requirements' => 'بكالوريوس صيدلة، ترخيص مزاولة المهنة، خبرة سنتين في المستشفيات',
                'status' => 'active'
            ],
            [
                'title' => 'مهندس كهرباء - طاقة متجددة',
                'work_place' => 'نيوم، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 6,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مهندس كهرباء متخصص في الطاقة المتجددة للعمل في مشاريع نيوم المستقبلية. فرصة للعمل على أحدث التقنيات.',
                'salary_min' => 12000,
                'salary_max' => 20000,
                'job_type' => 'دوام كامل',
                'skills' => 'Solar Energy, Wind Power, Grid Integration, MATLAB, AutoCAD',
                'requirements' => 'بكالوريوس هندسة كهربائية، خبرة 6 سنوات في الطاقة المتجددة، إجادة الإنجليزية',
                'status' => 'active'
            ],
            [
                'title' => 'مصور فوتوغرافي محترف',
                'work_place' => 'جدة، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 2,
                'work_experience' => 5,
                'work_field_id' => 2,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'نبحث عن مصور فوتوغرافي محترف للعمل على مشاريع متنوعة تشمل الأفراح، المناسبات، والتصوير التجاري.',
                'salary_min' => 4000,
                'salary_max' => 8000,
                'job_type' => 'دوام جزئي',
                'skills' => 'Portrait Photography, Event Photography, Lightroom, Photoshop',
                'requirements' => 'خبرة 5 سنوات في التصوير، معدات تصوير احترافية، أمثلة أعمال متميزة',
                'status' => 'active'
            ],
            [
                'title' => 'مترجم فوري - عربي/إنجليزي',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 4,
                'work_field_id' => 5,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مترجم فوري للعمل في المؤتمرات والاجتماعات الدولية. المطلوب إجادة تامة للعربية والإنجليزية.',
                'salary_min' => 8000,
                'salary_max' => 12000,
                'job_type' => 'دوام كامل',
                'skills' => 'الترجمة الفورية, الترجمة التحريرية, اللغة الإنجليزية, اللغة العربية',
                'requirements' => 'بكالوريوس ترجمة أو لغات، خبرة 4 سنوات، شهادات ترجمة معتمدة',
                'status' => 'active'
            ],
            [
                'title' => 'أخصائي علاج طبيعي',
                'work_place' => 'الدمام، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 3,
                'work_field_id' => 6,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب أخصائي علاج طبيعي للعمل في مركز تأهيل طبي. المطلوب خبرة في علاج الإصابات الرياضية والعظام.',
                'salary_min' => 6500,
                'salary_max' => 9500,
                'job_type' => 'دوام كامل',
                'skills' => 'العلاج الطبيعي, التأهيل الطبي, العلاج اليدوي, الأجهزة الطبية',
                'requirements' => 'بكالوريوس علاج طبيعي، ترخيص مزاولة المهنة، خبرة 3 سنوات',
                'status' => 'active'
            ],
            [
                'title' => 'مطور تطبيقات iOS - Swift',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 4,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'نبحث عن مطور تطبيقات iOS محترف لتطوير تطبيقات عالية الجودة. المطلوب خبرة في Swift وتطبيقات App Store.',
                'salary_min' => 9000,
                'salary_max' => 14000,
                'job_type' => 'دوام كامل',
                'skills' => 'Swift, iOS SDK, Xcode, Core Data, REST APIs',
                'requirements' => 'خبرة 4 سنوات في تطوير iOS، تطبيقات منشورة في App Store، معرفة بـ SwiftUI',
                'status' => 'active'
            ],
            [
                'title' => 'مدير مطعم',
                'work_place' => 'الخبر، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 7,
                'work_field_id' => 8,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مدير مطعم ذو خبرة لإدارة مطعم راقي. المطلوب خبرة في إدارة الفرق، خدمة العملاء، والعمليات اليومية.',
                'salary_min' => 8000,
                'salary_max' => 12000,
                'job_type' => 'دوام كامل',
                'skills' => 'إدارة المطاعم, خدمة العملاء, إدارة الفرق, المحاسبة',
                'requirements' => 'خبرة 7 سنوات في إدارة المطاعم، مهارات قيادية، معرفة بأنظمة نقاط البيع',
                'status' => 'active'
            ],
            [
                'title' => 'محلل أمن سيبراني',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 5,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب محلل أمن سيبراني لحماية الأنظمة والشبكات من التهديدات. المطلوب خبرة في اكتشاف ومنع الهجمات السيبرانية.',
                'salary_min' => 10000,
                'salary_max' => 16000,
                'job_type' => 'دوام كامل',
                'skills' => 'Cybersecurity, Penetration Testing, SIEM, Incident Response',
                'requirements' => 'بكالوريوس أمن معلومات، شهادات أمنية معتمدة، خبرة 5 سنوات',
                'status' => 'active'
            ],
            [
                'title' => 'مهندس معماري',
                'work_place' => 'جدة، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 6,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'نبحث عن مهندس معماري مبدع لتصميم المباني السكنية والتجارية. المطلوب خبرة في التصميم المعماري والإشراف على التنفيذ.',
                'salary_min' => 9000,
                'salary_max' => 15000,
                'job_type' => 'دوام كامل',
                'skills' => 'AutoCAD, 3ds Max, SketchUp, Revit, التصميم المعماري',
                'requirements' => 'بكالوريوس هندسة معمارية، خبرة 6 سنوات، أمثلة أعمال متميزة',
                'status' => 'active'
            ],
            [
                'title' => 'أخصائي تغذية علاجية',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'female',
                'education_level_id' => 1,
                'work_experience' => 3,
                'work_field_id' => 6,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوبة أخصائية تغذية علاجية للعمل في مستشفى. المطلوب خبرة في وضع الحميات العلاجية ومتابعة المرضى.',
                'salary_min' => 6000,
                'salary_max' => 9000,
                'job_type' => 'دوام كامل',
                'skills' => 'التغذية العلاجية, الحميات الطبية, تقييم التغذية, الاستشارات',
                'requirements' => 'بكالوريوس تغذية، ترخيص مزاولة المهنة، خبرة 3 سنوات في المستشفيات',
                'status' => 'active'
            ],
            [
                'title' => 'مطور مواقع - Full Stack',
                'work_place' => 'عن بُعد',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 5,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مطور مواقع Full Stack للعمل عن بُعد. المطلوب خبرة في تطوير الواجهات الأمامية والخلفية.',
                'salary_min' => 8000,
                'salary_max' => 13000,
                'job_type' => 'عن بُعد',
                'skills' => 'Laravel, Vue.js, MySQL, JavaScript, PHP, Git',
                'requirements' => 'خبرة 5 سنوات في تطوير المواقع، معرفة بـ Laravel و Vue.js، أمثلة مشاريع',
                'status' => 'active'
            ],
            [
                'title' => 'سائق شاحنة - نقل بضائع',
                'work_place' => 'الدمام، السعودية',
                'gender_preference' => 'male',
                'education_level_id' => 4,
                'work_experience' => 8,
                'work_field_id' => 8,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب سائق شاحنة محترف لنقل البضائع بين المدن. المطلوب خبرة واسعة ورخصة قيادة شاحنات سارية.',
                'salary_min' => 4500,
                'salary_max' => 6500,
                'job_type' => 'دوام كامل',
                'skills' => 'قيادة الشاحنات, معرفة الطرق, الصيانة الأساسية, السلامة',
                'requirements' => 'رخصة قيادة شاحنات، خبرة 8 سنوات، سجل قيادة نظيف',
                'status' => 'active'
            ],
            [
                'title' => 'مدرب لياقة بدنية',
                'work_place' => 'جدة، السعودية',
                'gender_preference' => 'male',
                'education_level_id' => 2,
                'work_experience' => 4,
                'work_field_id' => 6,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مدرب لياقة بدنية للعمل في نادي رياضي راقي. المطلوب خبرة في التدريب الشخصي وبرامج اللياقة.',
                'salary_min' => 5000,
                'salary_max' => 8000,
                'job_type' => 'دوام كامل',
                'skills' => 'التدريب الشخصي, برامج اللياقة, التغذية الرياضية, الإسعافات الأولية',
                'requirements' => 'شهادة تدريب معتمدة، خبرة 4 سنوات، لياقة بدنية عالية',
                'status' => 'active'
            ],
            [
                'title' => 'محاسب ضرائب',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 6,
                'work_field_id' => 3,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب محاسب ضرائب متخصص للعمل مع الشركات الكبرى. المطلوب خبرة واسعة في قوانين الضرائب السعودية.',
                'salary_min' => 8000,
                'salary_max' => 12000,
                'job_type' => 'دوام كامل',
                'skills' => 'ضريبة القيمة المضافة, ضريبة الدخل, النظم الضريبية, Excel المتقدم',
                'requirements' => 'بكالوريوس محاسبة، شهادة ضرائب معتمدة، خبرة 6 سنوات',
                'status' => 'active'
            ],
            [
                'title' => 'مهندس بترول',
                'work_place' => 'الظهران، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 1,
                'work_experience' => 8,
                'work_field_id' => 1,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب مهندس بترول للعمل في مشاريع استخراج وتكرير البترول. فرصة للعمل مع أحدث التقنيات في الصناعة.',
                'salary_min' => 15000,
                'salary_max' => 25000,
                'job_type' => 'دوام كامل',
                'skills' => 'Petroleum Engineering, Reservoir Simulation, Well Design, MATLAB',
                'requirements' => 'بكالوريوس هندسة بترول، خبرة 8 سنوات، إجادة الإنجليزية',
                'status' => 'active'
            ],
            [
                'title' => 'مصمم داخلي',
                'work_place' => 'الرياض، السعودية',
                'gender_preference' => 'female',
                'education_level_id' => 1,
                'work_experience' => 4,
                'work_field_id' => 2,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'نبحث عن مصممة داخلية مبدعة لتصميم المساحات السكنية والتجارية. المطلوب ذوق رفيع وخبرة في التصميم.',
                'salary_min' => 6000,
                'salary_max' => 10000,
                'job_type' => 'دوام كامل',
                'skills' => 'AutoCAD, 3ds Max, SketchUp, التصميم الداخلي, اختيار الألوان',
                'requirements' => 'بكالوريوس تصميم داخلي، خبرة 4 سنوات، أمثلة أعمال متميزة',
                'status' => 'active'
            ],
            [
                'title' => 'فني مختبر طبي',
                'work_place' => 'مكة المكرمة، السعودية',
                'gender_preference' => 'all',
                'education_level_id' => 2,
                'work_experience' => 3,
                'work_field_id' => 6,
                'country_of_graduation' => 1,
                'country_of_residence' => 1,
                'business_man_id' => 1,
                'description' => 'مطلوب فني مختبر طبي للعمل في مستشفى. المطلوب خبرة في إجراء التحاليل الطبية وتشغيل الأجهزة.',
                'salary_min' => 4500,
                'salary_max' => 7000,
                'job_type' => 'دوام كامل',
                'skills' => 'التحاليل الطبية, أجهزة المختبر, ضبط الجودة, السلامة المهنية',
                'requirements' => 'دبلوم مختبرات طبية، ترخيص مزاولة المهنة، خبرة 3 سنوات',
                'status' => 'active'
            ]
        ];

        foreach ($jobs as $job) {
            DB::table('jobs')->insert(array_merge($job, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]));
        }

        echo "تم إضافة " . count($jobs) . " وظيفة إضافية بنجاح!\n";
        echo "إجمالي الوظائف الآن: " . DB::table('jobs')->count() . " وظيفة\n";
    }
}
