version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fursati_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fursati_network

  db:
    image: mysql:8.0
    container_name: fursati_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fursati
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: fursati
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - fursati_network

  nginx:
    image: nginx:alpine
    container_name: fursati_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fursati_network

  redis:
    image: redis:alpine
    container_name: fursati_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fursati_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: fursati_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - fursati_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fursati_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - fursati_network

volumes:
  dbdata:
    driver: local

networks:
  fursati_network:
    driver: bridge 